# Dockerfile

FROM python:3.9

WORKDIR /app
COPY . /app

RUN pip install fastapi uvicorn scikit-learn joblib pydantic

EXPOSE 8000

CMD ["uvicorn", "model_api:app", "--host", "0.0.0.0", "--port", "8000"]
